import { useState, useEffect } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { toggleChecklistItem, calculateScore } from '../store/store';

export default function ChecklistModal({ isOpen, onClose, checklistData }) {
  const dispatch = useDispatch();
  const checklistCompleted = useSelector((state) => state.preparedness.checklistCompleted);

  // Parse checklist text into structured items
  const parseChecklist = (text) => {
    if (!text) return [];
    
    const lines = text.split('\n').filter(line => line.trim());
    const sections = [];
    let currentSection = null;

    lines.forEach(line => {
      const trimmed = line.trim();
      
      // Check if it's a heading (starts with # or ##)
      if (trimmed.startsWith('##')) {
        if (currentSection) sections.push(currentSection);
        currentSection = {
          title: trimmed.replace(/^##\s*/, ''),
          items: []
        };
      } else if (trimmed.startsWith('#')) {
        // Main title, skip
        return;
      } else if (trimmed.match(/^[•\-*]\s/)) {
        // It's a list item
        const item = trimmed.replace(/^[•\-*]\s*/, '');
        if (currentSection) {
          currentSection.items.push(item);
        }
      }
    });

    if (currentSection) sections.push(currentSection);
    return sections;
  };

  const sections = parseChecklist(checklistData?.checklist);

  const toggleItem = (sectionIndex, itemIndex) => {
    const key = `${sectionIndex}-${itemIndex}`;
    dispatch(toggleChecklistItem(key));
    // Recalculate score after toggling
    dispatch(calculateScore());
  };

  const getProgress = () => {
    const totalItems = sections.reduce((sum, section) => sum + section.items.length, 0);
    const checkedCount = Object.values(checklistCompleted).filter(Boolean).length;
    return totalItems > 0 ? Math.round((checkedCount / totalItems) * 100) : 0;
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 overflow-y-auto">
      {/* Backdrop */}
      <div 
        className="fixed inset-0 bg-black bg-opacity-50 transition-opacity"
        onClick={onClose}
      />

      {/* Modal */}
      <div className="flex min-h-full items-center justify-center p-4">
        <div className="relative bg-white dark:bg-slate-800 rounded-2xl shadow-2xl max-w-4xl w-full max-h-[90vh] overflow-hidden">
          {/* Header */}
          <div className="sticky top-0 bg-linear-to-r from-indigo-600 to-purple-600 text-white p-6 flex items-center justify-between">
            <div className="flex-1">
              <div className="flex items-center gap-3 mb-2">
                <span className="text-3xl">🤖</span>
                <h2 className="text-2xl font-bold">AI-Generated Emergency Checklist</h2>
              </div>
              {checklistData?.modelUsed && (
                <p className="text-sm opacity-90">
                  Generated by {checklistData.modelUsed} • {checklistData.language?.toUpperCase()}
                </p>
              )}
            </div>
            <button
              onClick={onClose}
              className="ml-4 p-2 hover:bg-white/20 rounded-lg transition"
            >
              <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>

          {/* Progress Bar */}
          {sections.length > 0 && (
            <div className="px-6 py-4 bg-slate-50 dark:bg-slate-900 border-b border-slate-200 dark:border-slate-700">
              <div className="flex items-center justify-between mb-2">
                <span className="text-sm font-medium text-slate-700 dark:text-slate-300">
                  Your Progress
                </span>
                <span className="text-sm font-bold text-indigo-600 dark:text-indigo-400">
                  {getProgress()}%
                </span>
              </div>
              <div className="h-2 bg-slate-200 dark:bg-slate-700 rounded-full overflow-hidden">
                <div 
                  className="h-full bg-linear-to-r from-indigo-500 to-purple-500 transition-all duration-500"
                  style={{ width: `${getProgress()}%` }}
                />
              </div>
            </div>
          )}

          {/* Content */}
          <div className="p-6 overflow-y-auto max-h-[calc(90vh-200px)]">
            {sections.length === 0 ? (
              <div className="text-center py-12">
                <div className="text-6xl mb-4">📋</div>
                <p className="text-slate-600 dark:text-slate-400">
                  Loading checklist...
                </p>
              </div>
            ) : (
              <div className="space-y-8">
                {sections.map((section, sectionIndex) => (
                  <div key={sectionIndex} className="space-y-4">
                    <h3 className="text-xl font-bold text-slate-900 dark:text-white flex items-center gap-2">
                      <span className="text-2xl">{getSectionIcon(section.title)}</span>
                      {section.title}
                    </h3>
                    <div className="space-y-2 pl-2">
                      {section.items.map((item, itemIndex) => {
                        const key = `${sectionIndex}-${itemIndex}`;
                        const isChecked = checklistCompleted[key] || false;
                        
                        return (
                          <label
                            key={itemIndex}
                            className={`flex items-start gap-3 p-3 rounded-lg cursor-pointer transition-all ${
                              isChecked
                                ? 'bg-green-50 dark:bg-green-900/20 border-green-200 dark:border-green-800'
                                : 'hover:bg-slate-50 dark:hover:bg-slate-700/50 border-transparent'
                            } border`}
                          >
                            <input
                              type="checkbox"
                              checked={isChecked}
                              onChange={() => toggleItem(sectionIndex, itemIndex)}
                              className="mt-1 w-5 h-5 text-indigo-600 rounded focus:ring-2 focus:ring-indigo-500"
                            />
                            <span className={`flex-1 ${
                              isChecked 
                                ? 'line-through text-slate-500 dark:text-slate-400' 
                                : 'text-slate-700 dark:text-slate-300'
                            }`}>
                              {item}
                            </span>
                          </label>
                        );
                      })}
                    </div>
                  </div>
                ))}
              </div>
            )}

            {/* Generated timestamp */}
            {checklistData?.generatedAt && (
              <div className="mt-8 pt-6 border-t border-slate-200 dark:border-slate-700 text-center">
                <p className="text-xs text-slate-500 dark:text-slate-400">
                  Generated on {new Date(checklistData.generatedAt).toLocaleString()}
                </p>
              </div>
            )}
          </div>

          {/* Footer Actions */}
          <div className="sticky bottom-0 bg-slate-50 dark:bg-slate-900 border-t border-slate-200 dark:border-slate-700 p-4 flex gap-3">
            <button
              onClick={() => {
                const text = checklistData?.checklist || '';
                navigator.clipboard.writeText(text);
                alert('Checklist copied to clipboard!');
              }}
              className="flex-1 px-4 py-2 bg-white dark:bg-slate-700 text-slate-700 dark:text-slate-300 border border-slate-300 dark:border-slate-600 rounded-lg hover:bg-slate-50 dark:hover:bg-slate-600 transition font-medium"
            >
              📋 Copy to Clipboard
            </button>
            <button
              onClick={() => window.print()}
              className="flex-1 px-4 py-2 bg-white dark:bg-slate-700 text-slate-700 dark:text-slate-300 border border-slate-300 dark:border-slate-600 rounded-lg hover:bg-slate-50 dark:hover:bg-slate-600 transition font-medium"
            >
              🖨️ Print
            </button>
            <button
              onClick={onClose}
              className="flex-1 px-4 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 transition font-medium"
            >
              Done
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}

function getSectionIcon(title) {
  const titleLower = title.toLowerCase();
  if (titleLower.includes('water') || titleLower.includes('food')) return '💧';
  if (titleLower.includes('medical') || titleLower.includes('health')) return '💊';
  if (titleLower.includes('document') || titleLower.includes('important')) return '📄';
  if (titleLower.includes('communication') || titleLower.includes('power')) return '🔌';
  if (titleLower.includes('pet')) return '🐾';
  if (titleLower.includes('child') || titleLower.includes('kid')) return '👶';
  if (titleLower.includes('elderly')) return '👴';
  if (titleLower.includes('personal')) return '👤';
  if (titleLower.includes('essential')) return '⭐';
  return '✓';
}
